spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javatechie
    username: root
    password: Thilanka@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


